export enum GovernanceEventName {
  OrganizationCreated = "OrganizationCreated",
  OrganizationUpdated = "OrganizationUpdated",
  OrganizationStatusChanged = "OrganizationStatusChanged",
  OrganizationFinalized = "OrganizationFinalized",
  BodyCreated = "BodyCreated",
  BodyUpdated = "BodyUpdated",
  RoleCreated = "RoleCreated",
  RoleUpdated = "RoleUpdated",
  MandateAssigned = "MandateAssigned",
  MandateRevoked = "MandateRevoked",
  PolicyRuleSet = "PolicyRuleSet",
  ExecutionTargetRuleUpdated = "ExecutionTargetRuleUpdated",
  ExecutionSelectorRuleUpdated = "ExecutionSelectorRuleUpdated",
  ProposalCreated = "ProposalCreated",
  ProposalApproved = "ProposalApproved",
  ProposalStatusChanged = "ProposalStatusChanged",
  ProposalVetoed = "ProposalVetoed",
  ProposalQueued = "ProposalQueued",
  ProposalExecuted = "ProposalExecuted",
  ProposalCancelled = "ProposalCancelled"
}
